version: "3.8"

services:
  backend:
    container_name: my_chatbot_backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - mongo
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    container_name: my_chatbot_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  mongo:
    container_name: my_chatbot_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # 개발 환경에서는 인증 없이 사용. 프로덕션에서는 환경 변수로 사용자/비밀번호 설정 권장
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: your_mongo_user
    #   MONGO_INITDB_ROOT_PASSWORD: your_mongo_password

volumes:
  mongo_data:
